"""Static rule catalog for Snitch.

Each entry describes a well-known security rule from a supported scanner.
This catalog is merged with rules dynamically discovered from scan findings.
"""

from typing import TypedDict


class RuleCatalogEntry(TypedDict):
    id: str
    name: str
    description: str
    severity: str          # critical | high | medium | low | info
    scanner: str           # checkov | semgrep | gitleaks | trivy | grype
    scan_type: str         # iac | sast | secrets | sca | container
    category: str
    remediation: str
    reference_url: str


RULE_CATALOG: list[RuleCatalogEntry] = [
    # -------------------------------------------------------------------------
    # Checkov — IaC / CIS AWS Foundations Benchmark Level 1
    # -------------------------------------------------------------------------
    {
        "id": "CKV_AWS_1",
        "name": "Ensure IAM policies that allow full '*:*' administrative privileges are not created",
        "description": "IAM policies should follow least-privilege. Granting '*' actions on '*' resources gives an identity unlimited access to all AWS services and resources.",
        "severity": "critical",
        "scanner": "checkov",
        "scan_type": "iac",
        "category": "IAM",
        "remediation": "Replace wildcard actions/resources with specific permissions. Use AWS managed policies where possible and scope resource ARNs narrowly.",
        "reference_url": "https://www.checkov.io/5.Policy%20Index/terraform.html",
    },
    {
        "id": "CKV_AWS_7",
        "name": "Ensure rotation for customer-created KMS CMKs is enabled",
        "description": "KMS key rotation reduces the risk of key compromise by limiting the amount of data encrypted under a single key version.",
        "severity": "medium",
        "scanner": "checkov",
        "scan_type": "iac",
        "category": "KMS",
        "remediation": "Set `enable_key_rotation = true` on the `aws_kms_key` resource.",
        "reference_url": "https://docs.aws.amazon.com/kms/latest/developerguide/rotate-keys.html",
    },
    {
        "id": "CKV_AWS_16",
        "name": "Ensure all data stored in the RDS instance is securely encrypted",
        "description": "RDS storage encryption protects data at rest from unauthorised access to the underlying storage. CIS AWS 2.3.",
        "severity": "high",
        "scanner": "checkov",
        "scan_type": "iac",
        "category": "RDS",
        "remediation": "Set `storage_encrypted = true` on the `aws_db_instance` resource.",
        "reference_url": "https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/Overview.Encryption.html",
    },
    {
        "id": "CKV_AWS_17",
        "name": "Ensure all data stored in the RDS instance is not publicly accessible",
        "description": "Publicly accessible RDS instances expose database endpoints to the internet. Only instances inside a VPC accessible from known networks should be reachable.",
        "severity": "high",
        "scanner": "checkov",
        "scan_type": "iac",
        "category": "RDS",
        "remediation": "Set `publicly_accessible = false` on the `aws_db_instance` resource.",
        "reference_url": "https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/USER_VPC.WorkingWithRDSInstanceinaVPC.html",
    },
    {
        "id": "CKV_AWS_18",
        "name": "Ensure the S3 bucket has access logging enabled",
        "description": "S3 server access logs provide detailed records of all requests made to a bucket — essential for security auditing and incident response. CIS AWS 2.6.",
        "severity": "medium",
        "scanner": "checkov",
        "scan_type": "iac",
        "category": "S3",
        "remediation": "Add a `logging` block to the `aws_s3_bucket` resource specifying a target bucket and prefix.",
        "reference_url": "https://docs.aws.amazon.com/AmazonS3/latest/userguide/ServerLogs.html",
    },
    {
        "id": "CKV_AWS_19",
        "name": "Ensure all data stored in the S3 bucket is securely encrypted at rest",
        "description": "Server-side encryption ensures data at rest in S3 is encrypted using AES-256 or AWS KMS keys.",
        "severity": "medium",
        "scanner": "checkov",
        "scan_type": "iac",
        "category": "S3",
        "remediation": "Add a `server_side_encryption_configuration` block to the `aws_s3_bucket` resource.",
        "reference_url": "https://docs.aws.amazon.com/AmazonS3/latest/userguide/serv-side-encryption.html",
    },
    {
        "id": "CKV_AWS_20",
        "name": "Ensure the S3 bucket does not allow public READ access via ACL",
        "description": "Publicly readable S3 buckets expose all objects to anonymous internet access. CIS AWS 2.1.",
        "severity": "high",
        "scanner": "checkov",
        "scan_type": "iac",
        "category": "S3",
        "remediation": "Remove `public-read` or `public-read-write` ACLs and apply `aws_s3_bucket_public_access_block`.",
        "reference_url": "https://docs.aws.amazon.com/AmazonS3/latest/userguide/access-control-block-public-access.html",
    },
    {
        "id": "CKV_AWS_24",
        "name": "Ensure no security groups allow ingress from 0.0.0.0/0 to port 22 (SSH)",
        "description": "Opening SSH to the entire internet significantly increases attack surface for brute-force and exploitation. CIS AWS 4.1.",
        "severity": "critical",
        "scanner": "checkov",
        "scan_type": "iac",
        "category": "Network",
        "remediation": "Restrict SSH access to known IP ranges or use a bastion host / VPN.",
        "reference_url": "https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/security-group-rules.html",
    },
    {
        "id": "CKV_AWS_25",
        "name": "Ensure no security groups allow ingress from 0.0.0.0/0 to port 3389 (RDP)",
        "description": "Unrestricted RDP access exposes Windows instances to brute-force attacks. CIS AWS 4.2.",
        "severity": "critical",
        "scanner": "checkov",
        "scan_type": "iac",
        "category": "Network",
        "remediation": "Restrict RDP to specific IP ranges or use Systems Manager Session Manager.",
        "reference_url": "https://docs.aws.amazon.com/AWSEC2/latest/WindowsGuide/connecting_to_windows_instance.html",
    },
    {
        "id": "CKV_AWS_36",
        "name": "Ensure CloudTrail log file validation is enabled",
        "description": "Log file validation creates a SHA-256 hash of each CloudTrail log, enabling detection of log tampering. CIS AWS 3.2.",
        "severity": "medium",
        "scanner": "checkov",
        "scan_type": "iac",
        "category": "Logging",
        "remediation": "Set `enable_log_file_validation = true` on the `aws_cloudtrail` resource.",
        "reference_url": "https://docs.aws.amazon.com/awscloudtrail/latest/userguide/cloudtrail-log-file-validation-intro.html",
    },
    {
        "id": "CKV_AWS_40",
        "name": "Ensure IAM policies are attached only to groups or roles",
        "description": "Attaching IAM policies directly to users makes permissions harder to manage at scale. CIS AWS 1.16.",
        "severity": "medium",
        "scanner": "checkov",
        "scan_type": "iac",
        "category": "IAM",
        "remediation": "Remove inline/direct policy attachments from `aws_iam_user_policy`. Use groups and roles instead.",
        "reference_url": "https://docs.aws.amazon.com/IAM/latest/UserGuide/best-practices.html",
    },
    {
        "id": "CKV_AWS_53",
        "name": "Ensure S3 bucket has block public ACLS enabled",
        "description": "BlockPublicAcls prevents new ACLs or object ACLs that grant public access from being set.",
        "severity": "high",
        "scanner": "checkov",
        "scan_type": "iac",
        "category": "S3",
        "remediation": "Set `block_public_acls = true` in `aws_s3_bucket_public_access_block`.",
        "reference_url": "https://docs.aws.amazon.com/AmazonS3/latest/userguide/access-control-block-public-access.html",
    },
    {
        "id": "CKV_AWS_54",
        "name": "Ensure S3 bucket has block public policy enabled",
        "description": "BlockPublicPolicy prevents new bucket policies that grant public access from being applied.",
        "severity": "high",
        "scanner": "checkov",
        "scan_type": "iac",
        "category": "S3",
        "remediation": "Set `block_public_policy = true` in `aws_s3_bucket_public_access_block`.",
        "reference_url": "https://docs.aws.amazon.com/AmazonS3/latest/userguide/access-control-block-public-access.html",
    },
    {
        "id": "CKV_AWS_55",
        "name": "Ensure S3 bucket has ignore public ACLs enabled",
        "description": "IgnorePublicAcls causes S3 to ignore public ACLs on bucket and objects, even if they exist.",
        "severity": "high",
        "scanner": "checkov",
        "scan_type": "iac",
        "category": "S3",
        "remediation": "Set `ignore_public_acls = true` in `aws_s3_bucket_public_access_block`.",
        "reference_url": "https://docs.aws.amazon.com/AmazonS3/latest/userguide/access-control-block-public-access.html",
    },
    {
        "id": "CKV_AWS_56",
        "name": "Ensure S3 bucket has restrict public buckets enabled",
        "description": "RestrictPublicBuckets prevents access by anonymous users even if a policy grants it.",
        "severity": "high",
        "scanner": "checkov",
        "scan_type": "iac",
        "category": "S3",
        "remediation": "Set `restrict_public_buckets = true` in `aws_s3_bucket_public_access_block`.",
        "reference_url": "https://docs.aws.amazon.com/AmazonS3/latest/userguide/access-control-block-public-access.html",
    },
    {
        "id": "CKV_AWS_57",
        "name": "Ensure the S3 bucket does not allow READ_ACP permissions to everyone",
        "description": "READ_ACP ACL grants anonymous users the ability to read bucket ACL configuration, facilitating reconnaissance.",
        "severity": "medium",
        "scanner": "checkov",
        "scan_type": "iac",
        "category": "S3",
        "remediation": "Remove public ACL grants and enforce bucket ownership controls.",
        "reference_url": "https://docs.aws.amazon.com/AmazonS3/latest/userguide/acls.html",
    },
    {
        "id": "CKV_AWS_67",
        "name": "Ensure CloudTrail is enabled in all regions",
        "description": "Multi-region CloudTrail captures API activity across all regions including global services. CIS AWS 3.1.",
        "severity": "high",
        "scanner": "checkov",
        "scan_type": "iac",
        "category": "Logging",
        "remediation": "Set `is_multi_region_trail = true` on the `aws_cloudtrail` resource.",
        "reference_url": "https://docs.aws.amazon.com/awscloudtrail/latest/userguide/receive-cloudtrail-log-files-from-multiple-regions.html",
    },
    {
        "id": "CKV_AWS_79",
        "name": "Ensure EC2 instance metadata service version 1 is not enabled (IMDSv2 required)",
        "description": "IMDSv1 is vulnerable to SSRF attacks that can leak IAM credentials from the metadata endpoint. IMDSv2 requires a session token, mitigating this risk.",
        "severity": "high",
        "scanner": "checkov",
        "scan_type": "iac",
        "category": "EC2",
        "remediation": "Set `http_tokens = 'required'` in the `metadata_options` block of `aws_instance` or `aws_launch_template`.",
        "reference_url": "https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/configuring-instance-metadata-service.html",
    },
    {
        "id": "CKV_AWS_2",
        "name": "Ensure Lambda function is not publicly accessible",
        "description": "Lambda functions with resource-based policies granting public invocation can be called by any AWS account or anonymous user.",
        "severity": "high",
        "scanner": "checkov",
        "scan_type": "iac",
        "category": "Lambda",
        "remediation": "Remove `aws_lambda_permission` grants with `principal = '*'`. Restrict to specific services or accounts.",
        "reference_url": "https://docs.aws.amazon.com/lambda/latest/dg/access-control-resource-based.html",
    },

    # -------------------------------------------------------------------------
    # Semgrep — SAST
    # -------------------------------------------------------------------------
    {
        "id": "python.django.security.injection.sql.sql-injection-using-db-cursor-fetchone",
        "name": "SQL injection via Django DB cursor",
        "description": "User-controlled input is passed directly into a raw SQL query via cursor.execute() without parameterisation, allowing SQL injection attacks.",
        "severity": "critical",
        "scanner": "semgrep",
        "scan_type": "sast",
        "category": "Injection",
        "remediation": "Use parameterised queries: `cursor.execute('SELECT * FROM t WHERE id = %s', [user_input])`.",
        "reference_url": "https://semgrep.dev/r/python.django.security.injection.sql",
    },
    {
        "id": "python.flask.security.xss.reflected-xss",
        "name": "Reflected XSS in Flask route",
        "description": "User-controlled data is rendered in an HTTP response without HTML encoding, allowing an attacker to inject malicious scripts.",
        "severity": "high",
        "scanner": "semgrep",
        "scan_type": "sast",
        "category": "XSS",
        "remediation": "Use Flask's `escape()` / Jinja2 auto-escaping. Never render `request` data directly.",
        "reference_url": "https://semgrep.dev/r/python.flask.security.xss",
    },
    {
        "id": "python.django.security.audit.csrf-exempt",
        "name": "CSRF protection disabled with @csrf_exempt",
        "description": "The @csrf_exempt decorator removes Django's built-in CSRF protection, exposing state-changing endpoints to cross-site request forgery.",
        "severity": "medium",
        "scanner": "semgrep",
        "scan_type": "sast",
        "category": "CSRF",
        "remediation": "Remove @csrf_exempt. Use Django's CsrfViewMiddleware and include `{% csrf_token %}` in forms.",
        "reference_url": "https://semgrep.dev/r/python.django.security.audit.csrf-exempt",
    },
    {
        "id": "python.lang.security.insecure-hash-algorithms.insecure-hash-algorithm-md5",
        "name": "Insecure hash algorithm: MD5",
        "description": "MD5 is cryptographically broken and must not be used for password hashing, certificates, or any security-sensitive purpose.",
        "severity": "medium",
        "scanner": "semgrep",
        "scan_type": "sast",
        "category": "Cryptography",
        "remediation": "Use SHA-256 or SHA-3 for checksums; use bcrypt/argon2/scrypt for password hashing.",
        "reference_url": "https://semgrep.dev/r/python.lang.security.insecure-hash-algorithms",
    },
    {
        "id": "python.lang.security.insecure-hash-algorithms.insecure-hash-algorithm-sha1",
        "name": "Insecure hash algorithm: SHA-1",
        "description": "SHA-1 is considered weak against collision attacks and should not be used for cryptographic purposes.",
        "severity": "medium",
        "scanner": "semgrep",
        "scan_type": "sast",
        "category": "Cryptography",
        "remediation": "Replace with SHA-256 or stronger. For passwords use bcrypt/argon2.",
        "reference_url": "https://semgrep.dev/r/python.lang.security.insecure-hash-algorithms",
    },
    {
        "id": "python.lang.security.audit.insecure-transport.requests.request-with-http",
        "name": "Credentials sent over unencrypted HTTP",
        "description": "HTTP requests (not HTTPS) expose credentials, tokens, and session data to man-in-the-middle attacks.",
        "severity": "low",
        "scanner": "semgrep",
        "scan_type": "sast",
        "category": "Transport Security",
        "remediation": "Always use `https://` URLs. Enforce HSTS on the server and verify SSL certs.",
        "reference_url": "https://semgrep.dev/r/python.lang.security.audit.insecure-transport",
    },
    {
        "id": "javascript.node.security.audit.path-traversal",
        "name": "Path traversal via user-supplied file path",
        "description": "User-controlled file paths without proper sanitisation can allow attackers to read or write arbitrary files on the server.",
        "severity": "high",
        "scanner": "semgrep",
        "scan_type": "sast",
        "category": "Path Traversal",
        "remediation": "Validate and normalise paths with `path.resolve()` and check they remain within the expected directory.",
        "reference_url": "https://semgrep.dev/r/javascript.node.security.audit.path-traversal",
    },
    {
        "id": "javascript.lang.security.audit.prototype-pollution",
        "name": "Prototype pollution vulnerability",
        "description": "Merging user-supplied objects without key sanitisation can inject properties into `Object.prototype`, affecting all objects in the application.",
        "severity": "high",
        "scanner": "semgrep",
        "scan_type": "sast",
        "category": "Injection",
        "remediation": "Sanitise keys by checking for `__proto__`, `constructor`, and `prototype` before merging. Use `Object.create(null)` for plain dictionaries.",
        "reference_url": "https://semgrep.dev/r/javascript.lang.security.audit.prototype-pollution",
    },
    {
        "id": "javascript.lang.security.audit.hardcoded-credentials",
        "name": "Hardcoded credentials in JavaScript source",
        "description": "Passwords, tokens, or API keys embedded in source code are exposed to anyone with code access and are often committed to version control.",
        "severity": "high",
        "scanner": "semgrep",
        "scan_type": "sast",
        "category": "Secrets",
        "remediation": "Move secrets to environment variables or a secrets manager (AWS Secrets Manager, HashiCorp Vault, etc.).",
        "reference_url": "https://semgrep.dev/r/javascript.lang.security.audit.hardcoded-credentials",
    },
    {
        "id": "python.lang.security.audit.subprocess.subprocess-shell-true",
        "name": "Command injection risk via subprocess with shell=True",
        "description": "Using `shell=True` with user-supplied input allows OS command injection, enabling full server compromise.",
        "severity": "critical",
        "scanner": "semgrep",
        "scan_type": "sast",
        "category": "Injection",
        "remediation": "Use a list of arguments instead of a shell string: `subprocess.run(['cmd', arg])` with `shell=False`.",
        "reference_url": "https://semgrep.dev/r/python.lang.security.audit.subprocess",
    },
    {
        "id": "python.django.security.audit.django-secret-key",
        "name": "Django SECRET_KEY exposed in settings",
        "description": "The Django SECRET_KEY should never be committed to source code. It is used for session signing and CSRF token generation.",
        "severity": "high",
        "scanner": "semgrep",
        "scan_type": "sast",
        "category": "Secrets",
        "remediation": "Load SECRET_KEY from an environment variable: `SECRET_KEY = os.environ['DJANGO_SECRET_KEY']`.",
        "reference_url": "https://semgrep.dev/r/python.django.security.audit.django-secret-key",
    },
    {
        "id": "python.flask.security.audit.redirect-to-unknown",
        "name": "Open redirect via unvalidated URL parameter",
        "description": "Redirecting to a user-supplied URL without validation enables phishing attacks by bouncing victims off a trusted domain.",
        "severity": "medium",
        "scanner": "semgrep",
        "scan_type": "sast",
        "category": "Open Redirect",
        "remediation": "Validate redirect URLs against an allowlist of trusted domains before issuing the redirect.",
        "reference_url": "https://semgrep.dev/r/python.flask.security.audit.redirect-to-unknown",
    },

    # -------------------------------------------------------------------------
    # Gitleaks — Secrets detection
    # -------------------------------------------------------------------------
    {
        "id": "generic.secrets.gitleaks.aws-access-token",
        "name": "AWS access key ID detected",
        "description": "A pattern matching AWS_ACCESS_KEY_ID was found in the codebase. Leaked AWS credentials allow full API access to the associated IAM identity.",
        "severity": "critical",
        "scanner": "gitleaks",
        "scan_type": "secrets",
        "category": "Cloud Credentials",
        "remediation": "Rotate the key immediately in the AWS console. Remove from code/git history using `git filter-repo`. Store in AWS Secrets Manager or environment variables.",
        "reference_url": "https://docs.aws.amazon.com/IAM/latest/UserGuide/id_credentials_access-keys.html",
    },
    {
        "id": "generic.secrets.gitleaks.github-pat",
        "name": "GitHub personal access token detected",
        "description": "A GitHub Personal Access Token (PAT) was found. PATs grant API access to GitHub repositories and organisations at the scopes they were created with.",
        "severity": "high",
        "scanner": "gitleaks",
        "scan_type": "secrets",
        "category": "Version Control Credentials",
        "remediation": "Revoke the token at https://github.com/settings/tokens. Use GitHub Actions secrets or a vault for CI/CD access.",
        "reference_url": "https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/managing-your-personal-access-tokens",
    },
    {
        "id": "generic.secrets.gitleaks.private-key",
        "name": "RSA/EC private key detected",
        "description": "A PEM-encoded private key was found in the codebase. Private keys must never be committed to source control.",
        "severity": "critical",
        "scanner": "gitleaks",
        "scan_type": "secrets",
        "category": "Cryptographic Keys",
        "remediation": "Revoke and regenerate the key pair. Store private keys in a secrets manager or HSM, never in source code.",
        "reference_url": "https://gitleaks.io/",
    },
    {
        "id": "generic.secrets.gitleaks.slack-webhook",
        "name": "Slack webhook URL detected",
        "description": "A Slack incoming webhook URL was found. Anyone with this URL can post messages to the associated channel.",
        "severity": "medium",
        "scanner": "gitleaks",
        "scan_type": "secrets",
        "category": "Webhook Credentials",
        "remediation": "Revoke and regenerate the Slack webhook. Store webhook URLs as environment secrets.",
        "reference_url": "https://api.slack.com/messaging/webhooks",
    },
    {
        "id": "generic.secrets.gitleaks.generic-api-key",
        "name": "Generic high-entropy API key detected",
        "description": "A high-entropy string matching common API key patterns was found. This may grant access to third-party services.",
        "severity": "high",
        "scanner": "gitleaks",
        "scan_type": "secrets",
        "category": "API Credentials",
        "remediation": "Rotate the API key with the issuing service. Move all secrets to environment variables or a secrets manager.",
        "reference_url": "https://gitleaks.io/",
    },
]

# Build a lookup dict for fast access
CATALOG_BY_ID: dict[str, RuleCatalogEntry] = {r["id"]: r for r in RULE_CATALOG}
